name: semux-discord
version: 0.1.0.0
github: githubuser/semux-discord
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2019 Author name here
extra-source-files:
  - README.md
  - ChangeLog.md
description: >-
  Please see the README on GitHub at
  <https://github.com/githubuser/semux-discord#readme>
dependencies:
  - base >= 4.7 && < 5
  - text
  - Decimal
  - aeson
  - aeson-pretty
  - bytestring
  - http-conduit
  - time
  - discord-haskell
  - unliftio
library:
  source-dirs: src
executables:
  semux-discord-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - semux-discord
tests:
  semux-discord-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - semux-discord
